//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRoom.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom
    {
        public Classroom()
        {
            this.ClassroomRoles = new HashSet<ClassroomRoles>();
        }
    
        public int Id { get; set; }
        public string Term { get; set; }
        public System.DateTime Year { get; set; }
        public string Campus { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<ClassroomRoles> ClassroomRoles { get; set; }
        public virtual ClassroomOptions ClassroomOption { get; set; }
    }
}
